apiName: "Matthijss API"

database:
# # the name of your JDBC driver
  driverClass: org.mariadb.jdbc.Driver
# # the username
  user: root
# # the password
  password: Chaud
# # the JDBC URL
  url: jdbc:mariadb://80.208.224.30/iprwc_matthijs

# # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MariaDBDialect

# # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

# # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

# # the minimum number of connections to keep open
  minSize: 8

# # the maximum number of connections to keep open
  maxSize: 32

# # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

assets:
  mappings:
    /assets: /
  overrides:
    /: ../iprwc-client/

server:
  rootPath: /api/*
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081